# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
ko:
  languageCode: "한국어"
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  contentDir: "content"
  wight: 1
  languagedirection: "ltr"

en:
  languageName: "English"
  weight: 2
  contentDir: "content"
  languagedirection: "ltr"

# Uncomment the lines below to configure your website in a second language.
#zh:
#  languageCode: zh-Hans
#  contentDir: content/zh
#  title: Chinese website title...
#  params:
#    description: Site description in Chinese...
#  menu:
#    main:
#      - name: 传
#        url: '#about'
#        weight: 1
