main:
  - name: "Home"
    pageRef: "/"             # ← 대문자 R (키 교정)
    weight: 10
    identifier: "home"

  - name: "About me"
    pageRef: "aboutme"         # ← content/about/index.md 로 연결
    parent: "home"
    weight: 11

  - name: "Projects"
    identifier: "projects"
    pageref: "project"
    weight: 20

  - name: "AI Game"
    parent: "projects"
    pageref: "project/game"
    weight: 21

  - name: "Image Gen"
    parent: "projects"
    pageref: "project/ai"
    weight: 22

  - name: "Malatang game"
    parent: "projects"
    pageref: "project/review"
    weight: 23

  - name: "Cloud Computing"
    parent: "projects"
    pageref: "project/data"
    weight: 24

  - name: "Web"
    parent: "projects"
    pageref: "project/web"
    weight: 25

  - name: Gallery
    url: /gallery/
    weight: 30

  - name: "About"
    url: "/about/"
    weight: 40

  - name: Contact
    identifier: "contact"
    url: /contact/
    weight: 60
      
  - name: "Info"
    parent: "contact"
    url: "/contact/"
    weight: 61

  - name: "Location"
    parent: "contact"
    url: "/contact/location/"
    weight: 62

