main:
  - name: "홈"
    page_ref: "/"      # 루트
    weight: 10
    identifier: "home"

  - name: "소개"
    page_ref: "home/about"  # ← 파일 경로 기준(언어 프리픽스 자동)
    parent: "home"
    weight: 11

  # 하위 메뉴들: parent 는 위 식별자 "projects"
  - name: "AI Game"
    parent: "projects"
    pageref: "project/game"
    weight: 21

  - name: "Image Gen"
    parent: "projects"
    pageref: "project/ai"  
    weight: 22

  - name: "Review"
    parent: "projects"
    pageref: "project/review"      
    weight: 23

  - name: "Data"
    parent: "projects"
    pageref: "project/data"
    weight: 24

  - name: "Web"
    parent: "projects"
    pageref: "project/web"
    weight: 25

  - name: "갤러리"
    url: "/gallery/"
    weight: 30

  - name: "이력"
    url: "/about/"
    weight: 40

  - name: "연락처"
    identifier: "contact"
    url: "/contact/"
    weight: 60

  - name: "연락처 정보"
    parent: "contact"
    url: "/contact/"
    weight: 61

  - name: "오시는 길"
    parent: "contact"
    url: "/contact/location/"
    weight: 62
