main:
  - name: 홈
    url: /
    weight: 10

  - name: 프로젝트
    url: /project/
    weight: 20

  - name: 갤러리
    url: /gallery/
    weight: 30

  - name: 이력
    url: /about/
    weight: 40

  - name: 블로그
    url: /blog/
    weight: 50

  - name: 연락처
    url: /contact/
    weight: 60
    identifier: contact

  - name: 연락처 정보
    parent: contact
    url: /contact/
    weight: 61

  - name: 오시는 길
    parent: contact
    url: /contact/location/
    weight: 62
