main:
  - name: home
    url: /
    weight: 10

  - name: projects
    url: /project/
    weight: 20

  - name: gallery
    url: /gallery/
    weight: 30

  - name: resume
    url: /about/
    weight: 40

  - name: blog
    url: /blog/
    weight: 50

  - name: contact
    url: /contact/
    weight: 60
