# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: home
    url: /
    weight: 10
  - name: projects
    url: /project/
    weight: 20
    identifier: projects
  - name: web
    parent: projects
    url: /project/web/
    weight: 21
  - name: data
    parent: projects
    url: /project/data/
    weight: 22
  - name: gallery
    url: /gallery/
    weight: 25
  - name: resume
    url: /resume/
    weight: 30
  - name: blog
    url: /blog/
    weight: 40
  - name: contact
    url: /contact/
    weight: 50
