main:
  - name: "home"
    url: "/"
    weight: 10
    identifier: "home"   # 부모 메뉴의 고유 ID

  - name: "about me"          # 드롭다운 항목
    url: "/home/about/"
    weight: 11
    parent: "home" 

  - name: "Projects"
    identifier: "projects"
    pageref: "project"
    weight: 20

  - name: "AI Game"
    parent: "projects"
    pageref: "project/game"
    weight: 21

  - name: "Image Gen"
    parent: "projects"
    pageref: "project/ai"
    weight: 22

  - name: "Review"
    parent: "projects"
    pageref: "project/review"
    weight: 23

  - name: "Data"
    parent: "projects"
    pageref: "project/data"
    weight: 24

  - name: "Web"
    parent: "projects"
    pageref: "project/web"
    weight: 25

  - name: gallery
    url: /gallery/
    weight: 30

  - name: "about"
    url: "/en/about/"
    weight: 40

  - name: contact
    url: /contact/
    weight: 60
      
  - name: "info"
    parent: "contact"
    url: "/contact/"
    weight: 61

  - name: "location"
    parent: "contact"
    url: "/contact/location/"
    weight: 62

