main:
  - name: "Home"
    page_ref: "home"
    weight: 10

  - name: "Projects"
    identifier: "projects"
    page_ref: "project"
    weight: 20

  - name: "AI Game"
    parent: "projects"
    page_ref: "project/game"
    weight: 21

  - name: "Image Gen"
    parent: "projects"
    page_ref: "project/AI"
    weight: 22

  - name: "Review"
    parent: "projects"
    page_ref: "project/Review"
    weight: 23

  - name: "Data"
    parent: "projects"
    page_ref: "project/data"
    weight: 24

  - name: "Web"
    parent: "projects"
    page_ref: "project/web"
    weight: 25

  - name: gallery
    url: /gallery/
    weight: 30

  - name: "about"
    url: "/en/about/index/"
    weight: 40

  - name: blog
    url: /blog/
    weight: 50

  - name: contact
    url: /contact/
    weight: 60
      
  - name: "info"
    parent: "contact"
    url: "/contact/"
    weight: 61

  - name: "location"
    parent: "contact"
    url: "/contact/location/"
    weight: 62

