# SITE SETUP
# Guide: https://docs.hugoblox.com/tutorial/
# Documentation: https://docs.hugoblox.com/
# YAML syntax: https://learnxinyminutes.com/docs/yaml/

# Appearance
appearance:
  theme_day: custom
  theme_night: custom
  font: minimal
  font_size: L

# SEO / Marketing
marketing:
  seo:
    site_type: Person
    local_business_type: ''
    org_name: ''
    # 핵심: "전북대 정사임"과 "전북대학교 정사임"을 모두 포함
    description: "전북대 정사임 | 전북대학교(전북대) 컴퓨터인공지능학부 정사임의 포트폴리오 — 프로젝트, 경력, 연락처"
    twitter: ''
  analytics:
    google_analytics: ''
    baidu_tongji: ''
    google_tag_manager: ''
    microsoft_clarity: ''
  verification:
    # HTML 태그 인증을 쓸 때만 값 유지. 파일 인증(HTML 업로드)을 쓸 거면 비워두세요.
    google: "imgsnoJoKrJNDEjMQU8gJzxcgUQSflHfnbp8imYKXKQ"

# Site meta (중복 제거, 단일 블록만 유지)
site:
  title: "전북대 정사임 | Jeong Saim (Jeonbuk National University)"
  description: "전북대 정사임 | 전북대학교(전북대) 컴퓨터인공지능학부 정사임의 포트폴리오 — 프로젝트, 경력, 연락처"
  keywords:
    - "전북대 정사임"
    - "전북대학교 정사임"
    - "Jeong Saim"
    - "Jeonbuk National University"
    - "컴퓨터인공지능학부"
    - "포트폴리오"

# Open Graph / Twitter 대표 이미지
images:
  - "https://samingming.github.io/preview.png"

# Custom assets (중복 제거)
custom_css:
  - "css/custom.css?v=25"
custom_js:
  - "js/center-filters.js?v=1"

# Header
header:
  navbar:
    enable: true
    align: r
    show_logo: true
    show_day_night: true
    show_search: true
    highlight_active_link: false
    show_title: false
    items:
      - type: languages

# Footer
footer:
  copyright:
    notice: "© {year} Me. This work is licensed under {license}"
    license:
      enable: true
      allow_derivatives: false
      share_alike: true
      allow_commercial: false

# Logo
logo:
  image: "logo.png"
  alt_text: "홈으로"
  link: "/"
  width: 130

# Localization
locale:
  date_format: "Jan 2, 2006"
  time_format: "3:04 PM"

# Features
features:
  syntax_highlighter:
    enable: true
    extra_languages:
      - r
      - latex
  math:
    enable: false
  privacy_pack:
    enable: false
  repository:
    url: "https://github.com/<username>/<repository>"
    content_dir: content
    branch: main
  avatar:
    gravatar: false
    shape: circle
  comment:
    provider: ''
    disqus:
      shortname: ''
      show_count: true
    commento:
      url: ''
    giscus:
      repo: ''
      repo_id: ''
      category: ''
      category_id: ''
  search:
    provider: wowchemy
    algolia:
      app_id: ''
      api_key: ''
      index_name: ''
      show_logo: false
  map:
    provider: openstreetmap
    api_key: ''
    zoom: 15

extensions:
  cms:
    branch: main
    local_backend: false
  academicons:
    enable: false

favicon: "images/favicon.png"
